Settings ivanka
green-fox-academy/Vulpes-Tribes-Frontend pull request #18
Opened 2019-01-18 10:54 UTC by hamsun7

2019-01-18 11:23 UTC, gyopak commented on src/app/kingdom-settings/kingdom-settings.service.ts
> +    console.log(this.kingdomService.getKingdom());
`log`

2019-01-18 11:23 UTC, gyopak commented on src/app/kingdom-settings/kingdom-settings.service.spec.ts
> +//    service.getSettings().subscribe(response => {
comments

2019-01-21 08:35 UTC, adamgyulavari requested changes

2019-01-21 08:35 UTC, adamgyulavari commented on src/app/kingdom-settings/kingdom-settings.service.spec.ts
> +     expect(kingdomService.getKingdom).toHaveBeenCalled();
@hamsun7 this test doesnt test anything

2019-01-21 08:35 UTC, adamgyulavari commented
@hamsun7 resolve conflicts

2019-01-21 14:32 UTC, closed without merging